### PR TITLE
Resolving some dashboard warnings

### LINKED ISSUE #110: Some errors on the setting dashboard
Some errors on the setting dashboard

Component Order	
Strict Standards: call_user_func() expects parameter 1 to be a valid callback, non-static method Admin_Apple_Settings_Section_Formatting::render_meta_component_order() should not be called statically, assuming $this from compatible context Admin_Apple_Settings_Section_Formatting in /srv/www/wordpress-default/wp-content/plugins/apple-news/admin/settings/class-admin-apple-settings-section.php on line 496

And when I failed to publish the article that already published using the plug-in version got from wordpress plugin successfully before, Got API error as well, Wonder if you can give some advice.

Thanks,
Wei

### PR DESCRIPTION
**Pull request by bcampeau**
Fixes #110

### CODE REVIEW

File: admin/settings/class-admin-apple-settings-section.php [hunk 1]
```diff
@@ -582,13 +582,22 @@ public function render_field( $args ) {
...
+				$field,
+				esc_attr( $name )
+			);
+		} else {
+			return sprintf(
+				$field,
+				esc_attr( $name ),
+				esc_attr( $value ),
+				intval( $size ),
+				$this->is_required( $name )
```
Comment (joshkadis) [inline admin/settings/class-admin-apple-settings-section.php]: Even though it can only be `'required'` or `''`, maybe late-escape anyway for consistency?

**Comment by joshkadis** [comment]
:hocho:
