### PR TITLE
APPLE-115 Fix YouTube Gutenberg embeds

### LINKED ISSUE #906: EmbedWebVideo not working properly with Gutenberg
YouTube, Vimeo, and generic Embed Gutenberg blocks containing YouTube and Vimeo embeds are not being properly converted to EmbedWebVideo components.

### PR DESCRIPTION
**Pull request by kevinfodness**
* Fixes YouTube and Vimeo embeds from the YouTube and Vimeo Gutenberg blocks.
* Refactors the test class for EmbedWebVideo to use the new base test class and conduct end-to-end testing.
* Adds support for generic Embed Gutenberg blocks that point at YouTube or Vimeo videos.
* Adds support for respecting the aspect ratio that is set on an embed in the Gutenberg block.

Fixes #906

### CODE REVIEW

File: tests/apple-exporter/components/test-class-embed-web-video.php [hunk 1]
```diff
@@ -6,219 +6,262 @@
...
+</div></figure>
+<!-- /wp:embed -->
+HTML;
+		$post_id      = self::factory()->post->create( [ 'post_content' => $post_content ] );
+		$json         = $this->get_json_for_post( $post_id );
+		$this->assertEquals(
+			[
+				'role'        => 'embedwebvideo',
+				'URL'         => 'https://www.youtube.com/embed/0qwALOOvUik',
+				'aspectRatio' => 1.4,
```
Comment (mogmarsh) [inline tests/apple-exporter/components/test-class-embed-web-video.php:144]: is this right? wouldn't it be 16/9 = 1.777 ?

**Review by mogmarsh — APPROVED** [review]
I had one question about a test, otherwise 👍

File: tests/apple-exporter/components/test-class-embed-web-video.php (hunk 1 above)
Comment (kevinfodness) [reply tests/apple-exporter/components/test-class-embed-web-video.php:144]: This is the function that tests the filter, and in the filter callback, we are explicitly setting this to 1.4. Otherwise, you're right, it would be 16/9 = 1.777.
