### PR TITLE
Fix dates in byline

### LINKED ISSUE #1035: Incorrect time stamp
### Description of the bug

Articles published to Apple News show a time of 8 hours earlier than the actual time of publication. We are CA, on Pacific time, and articles published at 7:45 a.m. local time are shown with a time stamp of the previous day at 11:45 p.m.

### Steps To Reproduce

publish article
experience incorrect time stamp

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by naxoc**
This fixes the dates in bylines. The were behind the site time by the UTC offset.

There is date handling in both `format_byline()` and `format_date()` and this makes them use the same date (post_date_gmt) to hand to `strtotime()` and `apple_news_date()` .

## How to reproduce

* I tested this on a fresh site where I didn't touch settings for Apple News at all.
* The site uses the timezone for Manaus, Brazil. 
* These are the dates on the post I tested on:

```
❯ wp post get 5 --fields=post_date_gmt,post_date
+---------------+---------------------+
| Field         | Value               |
+---------------+---------------------+
| post_date     | 2025-06-26 10:11:25 |
| post_date_gmt | 2025-06-26 14:11:25 |
+---------------+---------------------+
```
* Without the patch looking at the debug, the components -> byline said  "Jun 26, 2025 | 6:11 AM"
* With the patch it says:   "Jun 26, 2025 | 10:11 AM"

Note that this doesn't touch the other dates. This output is the same with and without the patch:
```
    "metadata": {
        "authors": [
            "Spongebob"
        ],
        "dateCreated": "2025-06-26T14:11:25+00:00",
        "dateModified": "2025-06-26T14:21:29+00:00",
        "datePublished": "2025-06-26T14:11:25+00:00",
        "canonicalURL": "https://fresh.test/?p=5",
        "generatorIdentifier": "publish-to-apple-news",
        "generatorName": "Publish To Apple News",
        "generatorVersion": "2.7.1"
    }
```

## Tests
I added a timezone-switcher to the tests. Not sure how robust that is, but it was quick :)

Fixes #1035

### CODE REVIEW

**Comment by naxoc** [comment]
Might be related to #1035

File: tests/admin/apple-actions/index/test-class-export.php [hunk 1]
```diff
@@ -163,32 +163,36 @@ public function test_shortcode_in_excerpt() {
...
+			$title   = 'My Title';
+			$content = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique quis justo sit amet eleifend. Praesent id metus semper, fermentum nibh at, malesuada enim. Mauris eget faucibus lectus. Vivamus iaculis eget urna non porttitor. Donec in dignissim neque. Vivamus ut ornare magna. Nulla eros nisi, maximus nec neque at, condimentum lobortis leo. Fusce in augue arcu. Curabitur lacus elit, venenatis a laoreet sit amet, imperdiet ac lorem. Curabitur sed leo sed ligula tempor feugiat. Cras in tellus et elit volutpat.</p>';
+
+			$post_id = $this->factory->post->create(
+				[
+					'post_title'   => $title,
+					'post_content' => $content,
+					'post_excerpt' => '',
+					'post_author'  => $user_id,
+					'post_date_gmt'    => '2016-08-26 16:00', // 4 hours ahead of Manaus time.
```
Comment (kevinfodness) [inline tests/admin/apple-actions/index/test-class-export.php]: Arrow alignment
```suggestion
					'post_title'    => $title,
					'post_content'  => $content,
					'post_excerpt'  => '',
					'post_author'   => $user_id,
					'post_date_gmt' => '2016-08-26 16:00', // 4 hours ahead of Manaus time.
```

**Review by kevinfodness — APPROVED** [review]
Excellent sleuthing! I was able to reproduce this on a fresh install as well. I left one suggestion related to formatting, otherwise this is good to merge. 🍣

File: tests/admin/apple-actions/index/test-class-export.php (hunk 1 above)
Comment (kevinfodness) [reply tests/admin/apple-actions/index/test-class-export.php]: Please see the output of the phpcs check - in addition to this fix, there are some other coding standards fixes that need to be applied in order for that test to pass and this PR to be able to be merged. Thanks!

Comment (naxoc) [reply tests/admin/apple-actions/index/test-class-export.php]: Woops. Ran `phpcbf` like I should have done to begin with :)

**Review by kevinfodness — APPROVED** [review]
🍣
