### PR TITLE
Fix: Get Unit tests passing for 2.4.1

### LINKED ISSUE #1027: Address failing unit tests
### Description of the bug

It appears that we need to do some more work to convert to Mantle Testkit, or there is another regression that needs to be fixed since [1022](https://github.com/alleyinteractive/apple-news/issues/1022)

### Steps To Reproduce

Run unit test suite

### Additional Information

AC 
Tests are passing

### PR DESCRIPTION
**Pull request by srtfisher**
Get tests passing on Apple News with TestKit.

Fixes #1027

### CODE REVIEW

File: tests/class-apple-news-testcase.php [hunk 1]
```diff
@@ -263,7 +263,9 @@ protected function add_http_response(
 				'body'     => $body,
 				'cookies'  => $cookies,
 				'filename' => $filename,
-				'headers'  => new Requests_Utility_CaseInsensitiveDictionary( $headers ),
+				'headers'  => class_exists( \WpOrg\Requests\Utility\CaseInsensitiveDictionary::class )
```
Comment (srtfisher) [inline tests/class-apple-news-testcase.php:266]: Change for WordPress 6.4 (I believe)

File: tests/bootstrap.php [hunk 2]
```diff
@@ -8,9 +8,6 @@
 
 /* phpcs:disable WordPressVIPMinimum.Files.IncludingFile.UsingVariable */
 
-const WP_TESTS_PHPUNIT_POLYFILLS_PATH = __DIR__ . '/../vendor/yoast/phpunit-polyfills'; // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
-
-const WP_TESTS_MULTISITE = 1; // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
```
Comment (srtfisher) [inline tests/bootstrap.php:13]: Moved to the workflow matrix

**Review by attackant — APPROVED** [review]
You sir, are a 🎩 and a 👨🏼‍🎓
