### PR TITLE
AN-132 Miscellaneous WordPress phpcs Error Fixes

### LINKED ISSUE #96: Update to adhere to coding standards
This plugin should be updated to adhere to WordPress Coding Standards. Much of it does already, it just needs a once-over to e.g. convert indentation to tabs.

### PR DESCRIPTION
**Pull request by kevinfodness**
* Addresses `WordPress.CSRF.NonceVerification.NoNonceVerification`.
* Addresses `WordPress.VIP.ValidatedSanitizedInput.MissingUnslash`.
* Addresses `WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized`.
* Addresses `WordPress.XSS.EscapeOutput.OutputNotEscaped`.
* Addresses `WordPress.PHP.YodaConditions.NotYoda`.
* Addresses `WordPress.VIP.RestrictedFunctions.user_meta_update_user_meta`.
* Addresses `WordPress.VIP.ValidatedSanitizedInput.InputNotValidated`.
* Addresses `WordPress.VIP.RestrictedFunctions.user_meta_delete_user_meta`.
* Addresses `WordPress.VIP.RestrictedFunctions.user_meta_get_user_meta`.
* Addresses `WordPress.VIP.FileSystemWritesDisallow.file_ops_delete`.
* Addresses `WordPress.Variables.GlobalVariables.OverrideProhibited`.

Fixes #96

### CODE REVIEW

File: admin/class-admin-apple-themes.php [hunk 1]
```diff
@@ -746,9 +759,15 @@ private function _save_edit_theme() {
 	 */
 	private function _set_theme() {
 
+		// Check the nonce.
```
Comment (kjbenk) [inline admin/class-admin-apple-themes.php]: You seem to use this same pattern a lot of checking a nonce, maybe you could make this a separate function in the future.

File: admin/class-admin-apple-notice.php [hunk 2]
```diff
@@ -237,7 +233,7 @@ private static function add_user_meta( $user_id, $value ) {
 		if ( defined( 'WPCOM_IS_VIP_ENV' ) && true === WPCOM_IS_VIP_ENV ) {
 			return update_user_attribute( $user_id, self::KEY, $values );
 		} else {
-			return update_user_meta( $user_id, self::KEY, $values );
+			return update_user_meta( $user_id, self::KEY, $values ); // phpcs:ignore WordPress.VIP.RestrictedFunctions.user_meta_update_user_meta
```
Comment (kjbenk) [inline admin/class-admin-apple-notice.php]: Since this is a plugin that is meant to work on VIP and Non-VIP sites, it might be worth disabling this restricted function sniff in `phpcs.xml` so that you do not need to iungore it each time you user it.

File: admin/class-admin-apple-json.php [hunk 3]
```diff
@@ -61,17 +80,35 @@ public function __construct() {
...
+		}
+
+		// Store the selected theme for use later.
+		if ( ! empty( $_POST['apple_news_theme'] ) ) {
+			$this->selected_theme = sanitize_text_field( wp_unslash( $_POST['apple_news_theme'] ) );
+		}
+
 		// Call the callback for the action for further processing.
-		call_user_func( $this->valid_actions[ $action ]['callback'] );
+		if ( isset( $this->valid_actions[ $action ]['callback'] ) ) {
```
Comment (kjbenk) [inline admin/class-admin-apple-json.php]: Should you also check `is_callable( $this->valid_actions[ $action ]['callback'] )` here?

File: admin/class-admin-apple-themes.php (hunk 1 above)
Comment (kevinfodness) [reply admin/class-admin-apple-themes.php]: I'd love to, but `phpcs` yells at you if you try to abstract the nonce check. It wants the nonce check at the top of every function that touches form data.

File: admin/class-admin-apple-notice.php (hunk 2 above)
Comment (kevinfodness) [reply admin/class-admin-apple-notice.php]: I'd rather have it pop the error and suppress it intentionally with the comment, just to be safe. It's also a signal to VIP that we know what we're doing :)
