### PR TITLE
AN-154 fix embeds

### LINKED ISSUE #599: Investigate compatibility of Instagram embeds with Gutenberg
Other embed formats (Facebook, Twitter, etc) have issues when used in Gutenberg and Apple News. Determine if Instagram has similar problems.

### PR DESCRIPTION
**Pull request by jomurgel**
Closes #599, #597, #596, #594
Also Closes: https://alleyinteractive.atlassian.net/browse/AN-154

- Fixes Facebook embeds, relies on WordPress to filter "success" embeds, and accommodate all mobile, short link and full facebook URLs. 
- Replaced multiple Facebook REGEX strings with single catch-all.
- Fixes YouTube embeds and new Gutenberg embed structure.
- Adds function to check for Gutenberg embed structure.
- Checks for excerpt before outputting the excerpt.

### Test With Apple News
Includes images and article.json for Gutenberg and the Classic Editor (rename article.json to test).
[apple-news-test.zip](https://github.com/alleyinteractive/apple-news/files/3153274/apple-news-test.zip)

NOTE: There will be image width warnings because the images used were small.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -4,4 +4,5 @@ tags
 composer.lock
 vendor
 npm-debug.log
-.idea
\ No newline at end of file
+.idea
+/.vscode
```
Comment (danbowles) [inline .gitignore]: you may not need the leading `/`

File: .gitignore [hunk 2]
```diff
@@ -4,4 +4,7 @@ tags
 composer.lock
 vendor
 npm-debug.log
-.idea
\ No newline at end of file
+.idea
+
+## IDE
+.vscode
```
Comment (kevinfodness) [inline .gitignore]: You can move `.idea` down here as well - that's the container for PhpStorm/WebStorm.

File: includes/apple-exporter/components/class-embed-web-video.php [hunk 3]
```diff
@@ -39,6 +41,7 @@ public static function is_embed_web_video( $node, $pattern ) {
 		return (
 			( 'p' === $node->nodeName && preg_match( $pattern, trim( $node->nodeValue ) ) ) // phpcs:ignore WordPress.NamingConventions.ValidVariableName.NotSnakeCaseMemberVar
 			|| ( 'iframe' === $node->nodeName && preg_match( $pattern, trim( $node->getAttribute( 'src' ) ) ) ) // phpcs:ignore WordPress.NamingConventions.ValidVariableName.NotSnakeCaseMemberVar
+			|| ( 'figure' === $node->nodeName && Component::is_gutenberg_embed_figure( $node ) ) // phpcs:ignore WordPress.NamingConventions.ValidVariableName.NotSnakeCaseMemberVar
```
Comment (kevinfodness) [inline includes/apple-exporter/components/class-embed-web-video.php]: Is this necessarily a Gutenberg convention? Does the default embed in the classic editor also do this? We may not want to name this function specifically as `gutenberg` in case this behavior exists in other contexts.

Comment (jomurgel) [reply includes/apple-exporter/components/class-embed-web-video.php]: Fair point. Will rename this function to `is_embed_figure` to be less specific.

**Comment by jomurgel** [comment]
Re: #594, Gutenberg/WordPress won't recognize an embed with the `?feature=oembed` argument. But the rest of the structure is now working with Classic and Gutenberg editors. Tested.

Re: #599, #596 Twitter and Instagram weren't working as a result of some order/testing issues with figures which wre resolved inside the `Image` and `Embed Web Video` Class/Components. Tested in the `json` tests above.

YouTube and Vimeo embed work with the default embedding (Classic Editor) or with the new YouTube Vimeo embed blocks (Gutenberg). Just pasting a YouTube/Vimeo URL will, by default, embed/add block automagically and work as expected.

Re: #597 Facebook embeds, similar to the Embed Web Video, was breaking in Gutenberg because of the new structure, and because of some URL regex issues with some facebook URLs needed to be updated.
