### PR TITLE
AN-55 Fix for widescreen text width

### LINKED ISSUE #233: Possible text flow issue on iPad for embedded images
See: https://wordpress.org/support/topic/large-right-margin/

### PR DESCRIPTION
**Pull request by kevinfodness**
* Sets the body text column span on non-center aligned layouts to be the same as the number of columns so that the text goes edge-to-edge.
* Fixes the logic for positioning images in centered and non-centered layouts to prevent bleed-over from the margins on non-centered layouts.
* Refactors the following classes for adherence to WordPress standards and PHP best practices:
  * Apple_Exporter\Builders\Builder
  * Apple_Exporter\Settings

Fixes #233.

### CODE REVIEW

File: includes/apple-exporter/builders/class-builder.php [hunk 1]
```diff
@@ -48,112 +68,110 @@ public function to_array() {
...
+	 * Gets the content title.
 	 *
 	 * @access protected
-	 * @return array
+	 * @return string The title from the content object, or a fallback title.
 	 */
-	protected function content_nodes() {
-		return $this->content->nodes();
+	protected function content_title() {
+		return $this->content->title() ?: __( 'Untitled Article', 'apple-news' );
```
Comment (romancandlethoughts) [inline includes/apple-exporter/builders/class-builder.php]: Not sure this is a valid concern, but seeing that WP is backward compat to php 5.2.x, this _might_ be an issue (though highly unlikely). Support for this shorthand syntax for ternary operations was introduced in 5.3.

Not sure this is a risk, just thought I'd flag it since this is a plugin.

File: includes/apple-exporter/builders/class-builder.php [hunk 2]
```diff
@@ -48,112 +68,110 @@ public function to_array() {
...
-	 * Gets a content setting by key.
+	 * Updates a content property.
 	 *
 	 * @access protected
-	 * @param string $name
-	 * @return mixed
 	 */
-	protected function get_setting( $name ) {
-		return $this->settings->get( $name );
+	protected function set_content_property( $name, $value ) {
```
Comment (romancandlethoughts) [inline includes/apple-exporter/builders/class-builder.php]: missing `@param` for these guys
