### PR TITLE
Properly removed ob_start on every page load, refactored page routing…

### LINKED ISSUE #56: Don't ob_start() on every page load
`ob_start()` shouldn't be included in `__construct()` of `Admin_Apple_News`, which is instantiated on every page load. I'm not sure why this hasn't broken things.

### PR DESCRIPTION
**Pull request by bcampeau**
… and template loading

Closes #56

### CODE REVIEW

File: admin/class-admin-apple-index-page.php [hunk 1]
```diff
@@ -44,16 +45,37 @@ public function setup_admin_page() {
...
 		);
 	}
 
 	/**
+	 * Decide which template to load for the Apple News admin page
+	 *
+	 * @access public
+	 */
+	public function admin_page() {
+		$id     = isset( $_GET['post_id'] ) ? intval( $_GET['post_id'] ) : null;
```
Comment (tomharrigan) [inline admin/class-admin-apple-index-page.php]: absint is better

File: admin/class-admin-apple-index-page.php [hunk 2]
```diff
@@ -66,36 +88,29 @@ public function setup_admin_page() {
...
-			return $this->delete_action( $id );
-		default:
-			wp_die( __( 'Invalid action: ', 'apple-news' ) . $action );
+			case self::namespace_action( 'settings' ):
+				return $this->settings_action( $id );
+			case self::namespace_action( 'export' ):
+				return $this->export_action( $id );
+			case self::namespace_action( 'push' ):
+				if ( ! $id ) {
+					$url  = menu_page_url( $this->plugin_slug . '_bulk_export', false );
```
Comment (tomharrigan) [inline admin/class-admin-apple-index-page.php]: extra space before `=`

**Comment by tomharrigan** [comment]
🐹
